# name of the software
name: Alphanumeric Twilio
# licence of the software
license: Apache 2.0
licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html

#baseurl: /AlphanumericTwilio

# list of additional links on the right of the top menu
headerLinks:
#  - title: GitHub
#    url: https://github.com/mistic100/jekyll-bootstrap-doc

# list if additional links on the footer
footerLinks:
  - title: <i class="fa fa-github"></i>GitHub
    url: https://github.com/BricksandMortar/AlphanumericTwilio
  - title: Issues
    url: https://github.com/BricksandMortar/AlphanumericTwilio/issues?state=open

# header
header:
  #color1: "#D43F3A"
  #color2: "#D4813A"
  color1: "#E64C29"
  color2: "#E64C29"

rockstore:
  url:

# google analytics
analytics:
  account:
  domain:

# github buttons
github:
  user: BricksandMortar
  repo: AlphanumericTwilio

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account: arranf


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile', vendor, script, .travis.yml]

gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
